spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@webfluxclustercourse.hafw3pf.mongodb.net/${DB_NAME:course-webflux}?retryWrites=true&w=majority
      auto-index-creation: true
  application:
    name: course-webflux